# Generated by Django 5.0 on 2024-07-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newscategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
