# Generated by Django 5.0 on 2024-07-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
