# Generated by Django 5.0 on 2024-07-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('social_link', models.URLField(max_length=5000)),
                ('phone_number', models.IntegerField(default=0)),
            ],
        ),
    ]
